---
- name: Configure SSH keys and dynamic /etc/hosts
  hosts: k8s_cluster
  become: yes
  gather_facts: yes

  tasks:

    - name: Ensure .ssh exists
      file:
        path: /home/ubuntu/.ssh
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0700'

    - name: Generate SSH key if not exists
      become_user: ubuntu
      command: ssh-keygen -t rsa -b 4096 -f /home/ubuntu/.ssh/id_rsa -N ""
      args:
        creates: /home/ubuntu/.ssh/id_rsa

    - name: Read master public key
      slurp:
        src: /home/ubuntu/.ssh/id_rsa.pub
      register: master_key
      when: inventory_hostname in groups['k8s_masters']

    - name: Set master key fact
      set_fact:
        master_ssh_key: "{{ master_key.content | b64decode }}"
      when: inventory_hostname in groups['k8s_masters']

    - name: Add SSH key to workers
      authorized_key:
        user: ubuntu
        state: present
        key: "{{ hostvars[groups['k8s_masters'][0]].master_ssh_key }}"
      when: inventory_hostname in groups['k8s_workers']

    - name: Configure dynamic /etc/hosts
      blockinfile:
        path: /etc/hosts
        block: |
          {% for host in groups['k8s_cluster'] %}
          {{ hostvars[host]['ansible_default_ipv4']['address'] }} {{ host }}
          {% endfor %}
        marker: "# {mark} ANSIBLE MANAGED K8S"
